# Generated by Django 2.2.6 on 2019-10-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_likes',
            new_name='users_like',
        ),
    ]
